### ISSUE TITLE
Есть поддержка песочницы?

### ISSUE THREAD

**Issue by rvalitov** [kiriunin/tinkoff-business-api#3]
В документации к проекту не нашел возможность использования песочницы https://business.tinkoff.ru/openapi/docs/#section/Pesochnica
Это не реализовано?
Полагаю, было бы очень полезно, можно было бы и тесты тогда написать.

**Comment by kiriunin** [comment]
Использовать песочницу можно, добавлю в документацию информацию о том как это делать

**Comment by kiriunin** [comment]
Сделано в 89671e3
