### ISSUE TITLE
Настройки прокси сервера

### ISSUE THREAD

**Issue by rvalitov** [kiriunin/tinkoff-business-api#4]
Все запросы к банку требуют статический IP. В некоторых проектах это достижимо только за счет использования прокси. Было бы здорово, если можно было в опциях для Guzzle прописать прокси сервер.

**Comment by kiriunin** [comment]
Изучу этот вопрос

**Comment by rvalitov** [comment]
Если что я тоже готов что-нибудь дописать, например, как раз это и связанное с этим #5  . Главное чтобы у нас было в идейном плане понимание того, что нужно/стоит делать.

**Comment by kiriunin** [comment]
Буду рад помощи 🙂 Мне лениво писать тесты, если честно. И для моих задач реализованных методов на данный момент достаточно. Так, что если есть желание, то можете расширить количество методов или написать тесты 😁

Эта задача перекликается с #5. Возможность передавать свои настройки в Guzzle добавлена в 75882bc
