### ISSUE TITLE
Операция по выписке возвращается как массив а не объект

### ISSUE THREAD

**Issue by rvalitov** [kiriunin/tinkoff-business-api#6]
Код из примера README:
```php
$statement=$tinkoff->accounts()->statement($request);
$operations = $statement->getOperation();
```
Ожидается, что в случае успешного выполнения `$operations` является массивом объектов `BankStatementOperation[]`.
И дальше ожидается, что можно делать так:
```php
foreach ($operations as $operation) {
    $inn=$operation->getRecipientInn();
}
```
Однако такой код не работает, и приводит к ошибке, потому что `$operation` в данном случае не объект, а массив.

**Comment by kiriunin** [comment]
Исправлю в следующей версии

**Comment by kiriunin** [comment]
Исправлено в e747121
