### ISSUE TITLE
Ошибка. Ответ 500

### ISSUE THREAD

**Issue by topermedia7** [kiriunin/tinkoff-business-api#7]
Здравствуйте!
Пытаюсь использовать код представленный в описании, но получаю постоянно http ответ 500

require('vendor/autoload.php');

// Пример 1. Получение ИНН компании
use Kiriunin\TinkoffBusinessApi\Tinkoff;
use Kiriunin\TinkoffBusinessApi\Schema\Entity;

// Создать клиент с токеном
$tinkoff = Tinkoff::create('мой токен');

// Сделать запрос на получение данных о компании и ее реквизитов
$companyInn = $tinkoff->company()
                    ->get()
                    ->getRequisites()
                    ->getInn();

**Comment by kiriunin** [comment]
Здравствуйте!

Не удалось воспроизвести вашу ошибку. Пришлите полный листинг кода, который вы пытаетесь выполнить и ответ сервера
